artifact_location: /Users/gollapsi/Documents/08_For_Roland_SG/Optimisation/runs/mlflow/0
creation_time: 1744378190993
experiment_id: '0'
last_update_time: 1744378190993
lifecycle_stage: active
name: Default
